package org.apiaddicts.apitools.apigen.generatorcore.config.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

@Data
public class Column {
    @JsonProperty("name")
    private String name;
    @JsonProperty("primary_key")
    private Boolean primaryKey = false;
    @JsonProperty("autogenerated")
    private Boolean autogenerated = false;
    @JsonProperty("sequence")
    private String sequence;
    @JsonProperty("unique")
    private Boolean unique = false; // FIXME analyze only used in DDL creation
    @JsonProperty("reference_column")
    private String referenceColumn;

    public Column() {
    }

    public Column(String name) {
        this.name = name;
    }

    public Column(String name, Boolean unique) {
        this.name = name;
        this.unique = unique;
    }

    public Column(String name, Boolean unique, String referenceColumn) {
        this.name = name;
        this.unique = unique;
        this.referenceColumn = referenceColumn;
    }

    public Column(String name, Boolean unique, Boolean primaryKey, String sequence) {
        this.name = name;
        this.unique = unique;
        this.primaryKey = primaryKey;
        this.sequence = sequence;
    }
}
